trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build the project"
    steps:
    - script: echo "Building the project..."
      displayName: "Run build script"

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Run tests"
    steps:
    - script: echo "Running tests..."
      displayName: "Run test script"

# Deploy Stage
- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
  - job: DeployJob
    displayName: "Deploy to environment"
    steps:
    - script: echo "Deploying to environment..."
      displayName: "Run deploy script"
